# Generated by Django 4.2 on 2023-04-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('idno', models.CharField(max_length=255)),
                ('atte', models.IntegerField()),
                ('grade', models.CharField(max_length=255)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
